// Sample personnel data for SAR platform
// CommonJS format for Node.js compatibility

const samplePersonnel = [
  {
    id: "1",
    name: "Emma Seery",
    type: "Personnel",
    status: "Available",
    skills: ["Blue Light Driver", "MRC Casualty Care", "Off-road Driver"],
    team: null,
    contact: "+44-7700-900123",
    callsign: "Duddon Emma",
  },
  {
    id: "2",
    name: "Peter Kay",
    type: "Personnel",
    status: "Available",
    skills: ["Hill Party Leader", "Basic Casualty Care"],
    team: null,
    contact: "+44-7700-900124",
    callsign: "Duddon Peter",
  },
  {
    id: "3",
    name: "Paddy Gannon",
    type: "Personnel",
    status: "Available",
    skills: ["Hill Party Leader", "MRC Casualty Care"],
    team: null,
    contact: "+44-7700-900125",
    callsign: "Duddon Paddy",
  },
  {
    id: "4",
    name: "Ellie Fidler",
    type: "Personnel",
    status: "Available",
    skills: ["DR", "MRC Casualty Care"],
    team: null,
    contact: "+44-7700-900126",
    callsign: "Duddon Ellie",
  },
  {
    id: "5",
    name: "Ollie Parsons",
    type: "Personnel",
    status: "Available",
    skills: ["Hill Party Leader", "MRC Casualty Care"],
    team: null,
    contact: "+44-7700-900127",
    callsign: "Duddon Ollie",
  },
  {
    id: "6",
    name: "Andy Chapman-Gibbs",
    type: "Personnel",
    status: "Available",
    skills: ["MRC Casualty Care", "Off-road Driver"],
    team: null,
    contact: "+44-7700-900128",
    callsign: "Duddon Andy",
  },
  {
    id: "7",
    name: "Dan King",
    type: "Personnel",
    status: "Available",
    skills: ["Basic Casualty Care", "Search Dog Handler"],
    team: null,
    contact: "+44-7700-900129",
    callsign: "Duddon Dan",
  },
  {
    id: "8",
    name: "Craig Stangroom",
    type: "Personnel",
    status: "Available",
    skills: ["Doctor", "Swift Water"],
    team: null,
    contact: "+44-7700-900130",
    callsign: "Duddon Craig",
  },
  {
    id: "9",
    name: "Rob McClymont",
    type: "Personnel",
    status: "Available",
    skills: ["Leader/Deputy", "Swift Water"],
    team: null,
    contact: "+44-7700-900131",
    callsign: "Duddon Rob",
  },
  {
    id: "10",
    name: "Tom Cox",
    type: "Personnel",
    status: "Available",
    skills: ["Search Dog Handler", "MRC Casualty Care"],
    team: null,
    contact: "+44-7700-900132",
    callsign: "Duddon Tom",
    dogName: "Ruby",
  },
  {
    id: "11",
    name: "Alistair Fale",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "12",
    name: "Amanda Seago",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "13",
    name: "Amy Reed",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "14",
    name: "Anna Marshall",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "15",
    name: "Cheryl Cox",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "16",
    name: "Chris Berry",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "17",
    name: "Chris Gill",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "18",
    name: "Craig Bangham",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "19",
    name: "Dave Binks",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "20",
    name: "Gary Lingard",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "21",
    name: "John Evanson",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "22",
    name: "John Nichols",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "23",
    name: "John Wealthall",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "24",
    name: "Jordan Price",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "25",
    name: "Kev Brooks",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "26",
    name: "Mick Pritchard",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "27",
    name: "Mike Margeson",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "28",
    name: "Mike Simpson",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "29",
    name: "Nigel Lister",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "30",
    name: "Paul Harrison",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "31",
    name: "Paul Makinson",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "32",
    name: "Petra Chapman Gibbs",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
  {
    id: "33",
    name: "Ryan Richards",
    type: "Personnel",
    status: "Not Available",
    skills: [],
    team: null,
    contact: "",
    callsign: "",
  },
];

module.exports = { samplePersonnel };
